package Demo.mapper;

import Demo.model.Lostfound;
import Demo.model.LostfoundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface LostfoundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int countByExample(LostfoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int deleteByExample(LostfoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int insert(Lostfound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int insertSelective(Lostfound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    List<Lostfound> selectByExample(LostfoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    Lostfound selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Lostfound record, @Param("example") LostfoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByExample(@Param("record") Lostfound record, @Param("example") LostfoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByPrimaryKeySelective(Lostfound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lostfound
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByPrimaryKey(Lostfound lostfound);

    List<Lostfound> findAll();  //查看所有数据

    int getCountById(Integer id);//根据id查记录  用于更新记录时候使用


    List<Lostfound> getAllLost(@Param("lflag") String lflag,@Param("udept")String udept);//查看所有的失物信息  ---失主  功能6

    List<Lostfound> getAllFound(@Param("lflag") String lflag,@Param("udept")String udept);//查看所有的得物信息  ---得主  功能7

    List<Lostfound> getAllThing(@Param("uid") String uid);//查看自己的信息



}