package Demo.mapper;

import Demo.model.Record;
import Demo.model.RecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int countByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int deleteByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    List<Record> selectByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    Record selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByExample(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByPrimaryKey(Record record);    //更改

    int getCountById(int rid);  //获取rid的个数

    List<Record> findAll();  //查看所有数据

    int getCountByRuid(String ruid);   //获取报备人员的个数

    int getCountByWid(String wid);  //获取维系人员的个数

    List<Record> getMessage(String udept);    //维修人员查看故障信息

    List<Record> getRMessage(String ruid);   //报备人员查看自己发布的报备信息

    List<Record> getWYMessage(@Param("wid") String wid,@Param("wstatic") String wstatic);   //维修人员查看已维修的报备信息

    List<Record> getWWMessage(@Param("wstatic") String wstatic,@Param("udept") String udept);   //维修人员查看待维修的报备信息





}