package Demo.mapper;

import Demo.model.Testtell;
import Demo.model.TesttellExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TesttellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int countByExample(TesttellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int deleteByExample(TesttellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int deleteByPrimaryKey(Integer testid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int insert(Testtell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int insertSelective(Testtell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    List<Testtell> selectByExample(TesttellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    Testtell selectByPrimaryKey(Integer testid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Testtell record, @Param("example") TesttellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByExample(@Param("record") Testtell record, @Param("example") TesttellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByPrimaryKeySelective(Testtell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int update(Testtell record);
    List<Testtell> findAll(String udept);
}