package Demo.mapper;

import Demo.model.Trade;
import Demo.model.TradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int countByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int deleteByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int insertSelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    List<Trade> selectByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    Trade selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByExample(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByPrimaryKeySelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    int updateByPrimaryKey(Trade record);

    int getCountById(int tid);  //获取rid的个数

    List<Trade> findAll(String udept);    //查看所有二手物品信息

    int getCountByTuid(String tuid);  //获取卖家的个数

    List<Trade> getMessageMJ(String tuid);    //查看自己发布得二手物品信息------卖家



}