package Demo.model;

import java.util.Date;
import java.util.Objects;

public class Lostfound {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lostfound.id
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lostfound.uid
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lostfound.des
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lostfound.time
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lostfound.lstatic
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String lstatic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lostfound.lflag
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String lflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lostfound.image
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String image;

    private String utel;

    private String udept;

    public Lostfound() {

    }

    public Lostfound(Integer id, String uid, String des, Date time, String lstatic, String lflag, String image, String utel, String udept) {
        this.id = id;
        this.uid = uid;
        this.des = des;
        this.time = time;
        this.lstatic = lstatic;
        this.lflag = lflag;
        this.image = image;
        this.utel = utel;
        this.udept = udept;
    }

    public String getUdept() {
        return udept;
    }

    public void setUdept(String udept) {
        this.udept = udept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lostfound.id
     *
     * @return the value of lostfound.id
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */



    public Integer getId() {
        return id;
    }

    public String getUtel() {
        return utel;
    }

    public void setUtel(String utel) {
        this.utel = utel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lostfound.id
     *
     * @param id the value for lostfound.id
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lostfound.uid
     *
     * @return the value of lostfound.uid
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lostfound.uid
     *
     * @param uid the value for lostfound.uid
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lostfound.des
     *
     * @return the value of lostfound.des
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lostfound.des
     *
     * @param des the value for lostfound.des
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lostfound.time
     *
     * @return the value of lostfound.time
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lostfound.time
     *
     * @param time the value for lostfound.time
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lostfound.lstatic
     *
     * @return the value of lostfound.lstatic
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public String getLstatic() {
        return lstatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lostfound.lstatic
     *
     * @param lstatic the value for lostfound.lstatic
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setLstatic(String lstatic) {
        this.lstatic = lstatic == null ? null : lstatic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lostfound.lflag
     *
     * @return the value of lostfound.lflag
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public String getLflag() {
        return lflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lostfound.lflag
     *
     * @param lflag the value for lostfound.lflag
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setLflag(String lflag) {
        this.lflag = lflag == null ? null : lflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lostfound.image
     *
     * @return the value of lostfound.image
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lostfound.image
     *
     * @param image the value for lostfound.image
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Lostfound)) return false;
        Lostfound lostfound = (Lostfound) o;
        return  Objects.equals(uid, lostfound.uid) &&
                Objects.equals(des, lostfound.des) &&
                Objects.equals(lstatic, lostfound.lstatic) &&
                Objects.equals(lflag, lostfound.lflag) &&
                Objects.equals(image, lostfound.image) &&
                Objects.equals(udept, lostfound.udept) &&
                Objects.equals(utel, lostfound.utel);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, uid, des, lstatic, lflag, image, utel,udept);
    }


    @Override
    public String toString() {
        return "Lostfound{" +
                "id=" + id +
                ", uid='" + uid + '\'' +
                ", des='" + des + '\'' +
                ", time=" + time +
                ", lstatic='" + lstatic + '\'' +
                ", lflag='" + lflag + '\'' +
                ", image='" + image + '\'' +
                ", utel='" + utel + '\'' +
                ", udept='" + udept + '\'' +
                '}';
    }
}