package Demo.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class Record implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.Rid
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.Ruid
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String ruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.Rdate
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Date rdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.Rdes
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String rdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.Radr
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String radr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.Rtype
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String rtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.Wid
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.Wstatic
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String wstatic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.Wdate
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Date wdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.image
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String image;

    private String utel;

    private String udept;

    public Record() {

    }

    public Record(Integer rid, String ruid, Date rdate, String rdes, String radr, String rtype, String wid, String wstatic, Date wdate, String image, String utel, String udept) {
        this.rid = rid;
        this.ruid = ruid;
        this.rdate = rdate;
        this.rdes = rdes;
        this.radr = radr;
        this.rtype = rtype;
        this.wid = wid;
        this.wstatic = wstatic;
        this.wdate = wdate;
        this.image = image;
        this.utel = utel;
        this.udept = udept;
    }

    public String getUdept() {
        return udept;
    }

    public void setUdept(String udept) {
        this.udept = udept;
    }

    public String getUtel() {
        return utel;
    }

    public void setUtel(String utel) {
        this.utel = utel;
    }

    public Integer getRid() {
        return rid;
    }

    public void setRid(Integer rid) {
        this.rid = rid;
    }

    public String getRuid() {
        return ruid;
    }

    public void setRuid(String ruid) {
        this.ruid = ruid;
    }

    public Date getRdate() {
        return rdate;
    }

    public void setRdate(Date rdate) {
        this.rdate = rdate;
    }

    public String getRdes() {
        return rdes;
    }

    public void setRdes(String rdes) {
        this.rdes = rdes;
    }

    public String getRadr() {
        return radr;
    }

    public void setRadr(String radr) {
        this.radr = radr;
    }

    public String getRtype() {
        return rtype;
    }

    public void setRtype(String rtype) {
        this.rtype = rtype;
    }

    public String getWid() {
        return wid;
    }

    public void setWid(String wid) {
        this.wid = wid;
    }

    public String getWstatic() {
        return wstatic;
    }

    public void setWstatic(String wstatic) {
        this.wstatic = wstatic;
    }

    public Date getWdate() {
        return wdate;
    }

    public void setWdate(Date wdate) {
        this.wdate = wdate;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Record)) return false;
        Record record = (Record) o;
        return Objects.equals(ruid, record.ruid) &&
                Objects.equals(rdate, record.rdate) &&
                Objects.equals(rdes, record.rdes) &&
                Objects.equals(radr, record.radr) &&
                Objects.equals(rtype, record.rtype) &&
                Objects.equals(wid, record.wid) &&
                Objects.equals(wstatic, record.wstatic) &&
                Objects.equals(wdate, record.wdate) &&
                Objects.equals(image, record.image)&&
                Objects.equals(udept, record.udept);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ruid, rdate, rdes, radr, rtype, wid, wstatic, wdate, image,udept);
    }

    @Override
    public String toString() {
        return "Record{" +
                "rid=" + rid +
                ", ruid='" + ruid + '\'' +
                ", rdate=" + rdate +
                ", rdes='" + rdes + '\'' +
                ", radr='" + radr + '\'' +
                ", rtype='" + rtype + '\'' +
                ", wid='" + wid + '\'' +
                ", wstatic='" + wstatic + '\'' +
                ", wdate=" + wdate +
                ", image='" + image + '\'' +
                ", utel='" + utel + '\'' +
                ", udept='" + udept + '\'' +
                '}';
    }
}