package Demo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public RecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andRidIsNull() {
            addCriterion("Rid is null");
            return (Criteria) this;
        }

        public Criteria andRidIsNotNull() {
            addCriterion("Rid is not null");
            return (Criteria) this;
        }

        public Criteria andRidEqualTo(Integer value) {
            addCriterion("Rid =", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotEqualTo(Integer value) {
            addCriterion("Rid <>", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThan(Integer value) {
            addCriterion("Rid >", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Rid >=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThan(Integer value) {
            addCriterion("Rid <", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThanOrEqualTo(Integer value) {
            addCriterion("Rid <=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidIn(List<Integer> values) {
            addCriterion("Rid in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotIn(List<Integer> values) {
            addCriterion("Rid not in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidBetween(Integer value1, Integer value2) {
            addCriterion("Rid between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotBetween(Integer value1, Integer value2) {
            addCriterion("Rid not between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andRuidIsNull() {
            addCriterion("Ruid is null");
            return (Criteria) this;
        }

        public Criteria andRuidIsNotNull() {
            addCriterion("Ruid is not null");
            return (Criteria) this;
        }

        public Criteria andRuidEqualTo(String value) {
            addCriterion("Ruid =", value, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidNotEqualTo(String value) {
            addCriterion("Ruid <>", value, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidGreaterThan(String value) {
            addCriterion("Ruid >", value, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidGreaterThanOrEqualTo(String value) {
            addCriterion("Ruid >=", value, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidLessThan(String value) {
            addCriterion("Ruid <", value, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidLessThanOrEqualTo(String value) {
            addCriterion("Ruid <=", value, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidLike(String value) {
            addCriterion("Ruid like", value, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidNotLike(String value) {
            addCriterion("Ruid not like", value, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidIn(List<String> values) {
            addCriterion("Ruid in", values, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidNotIn(List<String> values) {
            addCriterion("Ruid not in", values, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidBetween(String value1, String value2) {
            addCriterion("Ruid between", value1, value2, "ruid");
            return (Criteria) this;
        }

        public Criteria andRuidNotBetween(String value1, String value2) {
            addCriterion("Ruid not between", value1, value2, "ruid");
            return (Criteria) this;
        }

        public Criteria andRdateIsNull() {
            addCriterion("Rdate is null");
            return (Criteria) this;
        }

        public Criteria andRdateIsNotNull() {
            addCriterion("Rdate is not null");
            return (Criteria) this;
        }

        public Criteria andRdateEqualTo(Date value) {
            addCriterionForJDBCDate("Rdate =", value, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("Rdate <>", value, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdateGreaterThan(Date value) {
            addCriterionForJDBCDate("Rdate >", value, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Rdate >=", value, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdateLessThan(Date value) {
            addCriterionForJDBCDate("Rdate <", value, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Rdate <=", value, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdateIn(List<Date> values) {
            addCriterionForJDBCDate("Rdate in", values, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("Rdate not in", values, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Rdate between", value1, value2, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Rdate not between", value1, value2, "rdate");
            return (Criteria) this;
        }

        public Criteria andRdesIsNull() {
            addCriterion("Rdes is null");
            return (Criteria) this;
        }

        public Criteria andRdesIsNotNull() {
            addCriterion("Rdes is not null");
            return (Criteria) this;
        }

        public Criteria andRdesEqualTo(String value) {
            addCriterion("Rdes =", value, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesNotEqualTo(String value) {
            addCriterion("Rdes <>", value, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesGreaterThan(String value) {
            addCriterion("Rdes >", value, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesGreaterThanOrEqualTo(String value) {
            addCriterion("Rdes >=", value, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesLessThan(String value) {
            addCriterion("Rdes <", value, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesLessThanOrEqualTo(String value) {
            addCriterion("Rdes <=", value, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesLike(String value) {
            addCriterion("Rdes like", value, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesNotLike(String value) {
            addCriterion("Rdes not like", value, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesIn(List<String> values) {
            addCriterion("Rdes in", values, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesNotIn(List<String> values) {
            addCriterion("Rdes not in", values, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesBetween(String value1, String value2) {
            addCriterion("Rdes between", value1, value2, "rdes");
            return (Criteria) this;
        }

        public Criteria andRdesNotBetween(String value1, String value2) {
            addCriterion("Rdes not between", value1, value2, "rdes");
            return (Criteria) this;
        }

        public Criteria andRadrIsNull() {
            addCriterion("Radr is null");
            return (Criteria) this;
        }

        public Criteria andRadrIsNotNull() {
            addCriterion("Radr is not null");
            return (Criteria) this;
        }

        public Criteria andRadrEqualTo(String value) {
            addCriterion("Radr =", value, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrNotEqualTo(String value) {
            addCriterion("Radr <>", value, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrGreaterThan(String value) {
            addCriterion("Radr >", value, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrGreaterThanOrEqualTo(String value) {
            addCriterion("Radr >=", value, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrLessThan(String value) {
            addCriterion("Radr <", value, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrLessThanOrEqualTo(String value) {
            addCriterion("Radr <=", value, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrLike(String value) {
            addCriterion("Radr like", value, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrNotLike(String value) {
            addCriterion("Radr not like", value, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrIn(List<String> values) {
            addCriterion("Radr in", values, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrNotIn(List<String> values) {
            addCriterion("Radr not in", values, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrBetween(String value1, String value2) {
            addCriterion("Radr between", value1, value2, "radr");
            return (Criteria) this;
        }

        public Criteria andRadrNotBetween(String value1, String value2) {
            addCriterion("Radr not between", value1, value2, "radr");
            return (Criteria) this;
        }

        public Criteria andRtypeIsNull() {
            addCriterion("Rtype is null");
            return (Criteria) this;
        }

        public Criteria andRtypeIsNotNull() {
            addCriterion("Rtype is not null");
            return (Criteria) this;
        }

        public Criteria andRtypeEqualTo(String value) {
            addCriterion("Rtype =", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotEqualTo(String value) {
            addCriterion("Rtype <>", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeGreaterThan(String value) {
            addCriterion("Rtype >", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeGreaterThanOrEqualTo(String value) {
            addCriterion("Rtype >=", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeLessThan(String value) {
            addCriterion("Rtype <", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeLessThanOrEqualTo(String value) {
            addCriterion("Rtype <=", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeLike(String value) {
            addCriterion("Rtype like", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotLike(String value) {
            addCriterion("Rtype not like", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeIn(List<String> values) {
            addCriterion("Rtype in", values, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotIn(List<String> values) {
            addCriterion("Rtype not in", values, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeBetween(String value1, String value2) {
            addCriterion("Rtype between", value1, value2, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotBetween(String value1, String value2) {
            addCriterion("Rtype not between", value1, value2, "rtype");
            return (Criteria) this;
        }

        public Criteria andWidIsNull() {
            addCriterion("Wid is null");
            return (Criteria) this;
        }

        public Criteria andWidIsNotNull() {
            addCriterion("Wid is not null");
            return (Criteria) this;
        }

        public Criteria andWidEqualTo(String value) {
            addCriterion("Wid =", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotEqualTo(String value) {
            addCriterion("Wid <>", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidGreaterThan(String value) {
            addCriterion("Wid >", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidGreaterThanOrEqualTo(String value) {
            addCriterion("Wid >=", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLessThan(String value) {
            addCriterion("Wid <", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLessThanOrEqualTo(String value) {
            addCriterion("Wid <=", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLike(String value) {
            addCriterion("Wid like", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotLike(String value) {
            addCriterion("Wid not like", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidIn(List<String> values) {
            addCriterion("Wid in", values, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotIn(List<String> values) {
            addCriterion("Wid not in", values, "wid");
            return (Criteria) this;
        }

        public Criteria andWidBetween(String value1, String value2) {
            addCriterion("Wid between", value1, value2, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotBetween(String value1, String value2) {
            addCriterion("Wid not between", value1, value2, "wid");
            return (Criteria) this;
        }

        public Criteria andWstaticIsNull() {
            addCriterion("Wstatic is null");
            return (Criteria) this;
        }

        public Criteria andWstaticIsNotNull() {
            addCriterion("Wstatic is not null");
            return (Criteria) this;
        }

        public Criteria andWstaticEqualTo(String value) {
            addCriterion("Wstatic =", value, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticNotEqualTo(String value) {
            addCriterion("Wstatic <>", value, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticGreaterThan(String value) {
            addCriterion("Wstatic >", value, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticGreaterThanOrEqualTo(String value) {
            addCriterion("Wstatic >=", value, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticLessThan(String value) {
            addCriterion("Wstatic <", value, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticLessThanOrEqualTo(String value) {
            addCriterion("Wstatic <=", value, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticLike(String value) {
            addCriterion("Wstatic like", value, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticNotLike(String value) {
            addCriterion("Wstatic not like", value, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticIn(List<String> values) {
            addCriterion("Wstatic in", values, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticNotIn(List<String> values) {
            addCriterion("Wstatic not in", values, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticBetween(String value1, String value2) {
            addCriterion("Wstatic between", value1, value2, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWstaticNotBetween(String value1, String value2) {
            addCriterion("Wstatic not between", value1, value2, "wstatic");
            return (Criteria) this;
        }

        public Criteria andWdateIsNull() {
            addCriterion("Wdate is null");
            return (Criteria) this;
        }

        public Criteria andWdateIsNotNull() {
            addCriterion("Wdate is not null");
            return (Criteria) this;
        }

        public Criteria andWdateEqualTo(Date value) {
            addCriterionForJDBCDate("Wdate =", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("Wdate <>", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateGreaterThan(Date value) {
            addCriterionForJDBCDate("Wdate >", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Wdate >=", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateLessThan(Date value) {
            addCriterionForJDBCDate("Wdate <", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Wdate <=", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateIn(List<Date> values) {
            addCriterionForJDBCDate("Wdate in", values, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("Wdate not in", values, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Wdate between", value1, value2, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Wdate not between", value1, value2, "wdate");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 06 20:21:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}