package Demo.model;

import java.util.Date;

public class Testtell {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testtell.testId
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Integer testid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testtell.testName
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String testname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testtell.testDate
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Date testdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testtell.testArea
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String testarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testtell.image
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String image;

    private String udept;

    public Testtell() {

    }

    public Testtell(Integer testid, String testname, Date testdate, String testarea, String image, String udept) {
        this.testid = testid;
        this.testname = testname;
        this.testdate = testdate;
        this.testarea = testarea;
        this.image = image;
        this.udept = udept;
    }

    public String getUdept() {
        return udept;
    }

    public void setUdept(String udept) {
        this.udept = udept;
    }

    public Integer getTestid() {
        return testid;
    }

    public void setTestid(Integer testid) {
        this.testid = testid;
    }

    public String getTestname() {
        return testname;
    }

    public void setTestname(String testname) {
        this.testname = testname;
    }

    public Date getTestdate() {
        return testdate;
    }

    public void setTestdate(Date testdate) {
        this.testdate = testdate;
    }

    public String getTestarea() {
        return testarea;
    }

    public void setTestarea(String testarea) {
        this.testarea = testarea;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Override
    public String toString() {
        return "Testtell{" +
                "testid=" + testid +
                ", testname='" + testname + '\'' +
                ", testdate=" + testdate +
                ", testarea='" + testarea + '\'' +
                ", image='" + image + '\'' +
                ", udept='" + udept + '\'' +
                '}';
    }
}