package Demo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TesttellExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public TesttellExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTestidIsNull() {
            addCriterion("testId is null");
            return (Criteria) this;
        }

        public Criteria andTestidIsNotNull() {
            addCriterion("testId is not null");
            return (Criteria) this;
        }

        public Criteria andTestidEqualTo(Integer value) {
            addCriterion("testId =", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidNotEqualTo(Integer value) {
            addCriterion("testId <>", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidGreaterThan(Integer value) {
            addCriterion("testId >", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidGreaterThanOrEqualTo(Integer value) {
            addCriterion("testId >=", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidLessThan(Integer value) {
            addCriterion("testId <", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidLessThanOrEqualTo(Integer value) {
            addCriterion("testId <=", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidIn(List<Integer> values) {
            addCriterion("testId in", values, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidNotIn(List<Integer> values) {
            addCriterion("testId not in", values, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidBetween(Integer value1, Integer value2) {
            addCriterion("testId between", value1, value2, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidNotBetween(Integer value1, Integer value2) {
            addCriterion("testId not between", value1, value2, "testid");
            return (Criteria) this;
        }

        public Criteria andTestnameIsNull() {
            addCriterion("testName is null");
            return (Criteria) this;
        }

        public Criteria andTestnameIsNotNull() {
            addCriterion("testName is not null");
            return (Criteria) this;
        }

        public Criteria andTestnameEqualTo(String value) {
            addCriterion("testName =", value, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameNotEqualTo(String value) {
            addCriterion("testName <>", value, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameGreaterThan(String value) {
            addCriterion("testName >", value, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameGreaterThanOrEqualTo(String value) {
            addCriterion("testName >=", value, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameLessThan(String value) {
            addCriterion("testName <", value, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameLessThanOrEqualTo(String value) {
            addCriterion("testName <=", value, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameLike(String value) {
            addCriterion("testName like", value, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameNotLike(String value) {
            addCriterion("testName not like", value, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameIn(List<String> values) {
            addCriterion("testName in", values, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameNotIn(List<String> values) {
            addCriterion("testName not in", values, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameBetween(String value1, String value2) {
            addCriterion("testName between", value1, value2, "testname");
            return (Criteria) this;
        }

        public Criteria andTestnameNotBetween(String value1, String value2) {
            addCriterion("testName not between", value1, value2, "testname");
            return (Criteria) this;
        }

        public Criteria andTestdateIsNull() {
            addCriterion("testDate is null");
            return (Criteria) this;
        }

        public Criteria andTestdateIsNotNull() {
            addCriterion("testDate is not null");
            return (Criteria) this;
        }

        public Criteria andTestdateEqualTo(Date value) {
            addCriterion("testDate =", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateNotEqualTo(Date value) {
            addCriterion("testDate <>", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateGreaterThan(Date value) {
            addCriterion("testDate >", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateGreaterThanOrEqualTo(Date value) {
            addCriterion("testDate >=", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateLessThan(Date value) {
            addCriterion("testDate <", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateLessThanOrEqualTo(Date value) {
            addCriterion("testDate <=", value, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateIn(List<Date> values) {
            addCriterion("testDate in", values, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateNotIn(List<Date> values) {
            addCriterion("testDate not in", values, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateBetween(Date value1, Date value2) {
            addCriterion("testDate between", value1, value2, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestdateNotBetween(Date value1, Date value2) {
            addCriterion("testDate not between", value1, value2, "testdate");
            return (Criteria) this;
        }

        public Criteria andTestareaIsNull() {
            addCriterion("testArea is null");
            return (Criteria) this;
        }

        public Criteria andTestareaIsNotNull() {
            addCriterion("testArea is not null");
            return (Criteria) this;
        }

        public Criteria andTestareaEqualTo(String value) {
            addCriterion("testArea =", value, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaNotEqualTo(String value) {
            addCriterion("testArea <>", value, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaGreaterThan(String value) {
            addCriterion("testArea >", value, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaGreaterThanOrEqualTo(String value) {
            addCriterion("testArea >=", value, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaLessThan(String value) {
            addCriterion("testArea <", value, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaLessThanOrEqualTo(String value) {
            addCriterion("testArea <=", value, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaLike(String value) {
            addCriterion("testArea like", value, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaNotLike(String value) {
            addCriterion("testArea not like", value, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaIn(List<String> values) {
            addCriterion("testArea in", values, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaNotIn(List<String> values) {
            addCriterion("testArea not in", values, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaBetween(String value1, String value2) {
            addCriterion("testArea between", value1, value2, "testarea");
            return (Criteria) this;
        }

        public Criteria andTestareaNotBetween(String value1, String value2) {
            addCriterion("testArea not between", value1, value2, "testarea");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table testtell
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 06 20:21:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table testtell
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}