package Demo.model;

import java.util.Objects;

public class Trade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.Tid
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.Tdes
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String tdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.Tuid
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String tuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.Tprice
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Double tprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.image
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String image;

    private String utel;

    private String udept;

    public Trade() {

    }


    public Trade(Integer tid, String tdes, String tuid, Double tprice, String image, String utel, String udept) {
        this.tid = tid;
        this.tdes = tdes;
        this.tuid = tuid;
        this.tprice = tprice;
        this.image = image;
        this.utel = utel;
        this.udept = udept;
    }

    public String getUdept() {
        return udept;
    }

    public void setUdept(String udept) {
        this.udept = udept;
    }

    public Integer getTid() {
        return tid;
    }

    public void setTid(Integer tid) {
        this.tid = tid;
    }

    public String getTdes() {
        return tdes;
    }

    public void setTdes(String tdes) {
        this.tdes = tdes;
    }

    public String getTuid() {
        return tuid;
    }

    public void setTuid(String tuid) {
        this.tuid = tuid;
    }

    public Double getTprice() {
        return tprice;
    }

    public void setTprice(Double tprice) {
        this.tprice = tprice;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getUtel() {
        return utel;
    }

    public void setUtel(String utel) {
        this.utel = utel;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Trade)) return false;
        Trade trade = (Trade) o;
        return Objects.equals(tdes, trade.tdes) &&
                Objects.equals(tuid, trade.tuid) &&
                Objects.equals(tprice, trade.tprice) &&
                Objects.equals(image, trade.image) &&
                Objects.equals(udept, trade.udept)&&
                Objects.equals(utel, trade.utel);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tdes, tuid, tprice, image, utel,udept);
    }

    @Override
    public String toString() {
        return "Trade{" +
                "tid=" + tid +
                ", tdes='" + tdes + '\'' +
                ", tuid='" + tuid + '\'' +
                ", tprice=" + tprice +
                ", image='" + image + '\'' +
                ", utel='" + utel + '\'' +
                ", udept='" + udept + '\'' +
                '}';
    }
}