package Demo.model;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("Uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("Uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("Uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("Uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("Uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("Uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("Uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("Uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("Uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("Uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("Uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("Uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("Uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("Uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUpsdIsNull() {
            addCriterion("Upsd is null");
            return (Criteria) this;
        }

        public Criteria andUpsdIsNotNull() {
            addCriterion("Upsd is not null");
            return (Criteria) this;
        }

        public Criteria andUpsdEqualTo(String value) {
            addCriterion("Upsd =", value, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdNotEqualTo(String value) {
            addCriterion("Upsd <>", value, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdGreaterThan(String value) {
            addCriterion("Upsd >", value, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdGreaterThanOrEqualTo(String value) {
            addCriterion("Upsd >=", value, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdLessThan(String value) {
            addCriterion("Upsd <", value, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdLessThanOrEqualTo(String value) {
            addCriterion("Upsd <=", value, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdLike(String value) {
            addCriterion("Upsd like", value, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdNotLike(String value) {
            addCriterion("Upsd not like", value, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdIn(List<String> values) {
            addCriterion("Upsd in", values, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdNotIn(List<String> values) {
            addCriterion("Upsd not in", values, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdBetween(String value1, String value2) {
            addCriterion("Upsd between", value1, value2, "upsd");
            return (Criteria) this;
        }

        public Criteria andUpsdNotBetween(String value1, String value2) {
            addCriterion("Upsd not between", value1, value2, "upsd");
            return (Criteria) this;
        }

        public Criteria andUgradeIsNull() {
            addCriterion("Ugrade is null");
            return (Criteria) this;
        }

        public Criteria andUgradeIsNotNull() {
            addCriterion("Ugrade is not null");
            return (Criteria) this;
        }

        public Criteria andUgradeEqualTo(Integer value) {
            addCriterion("Ugrade =", value, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUgradeNotEqualTo(Integer value) {
            addCriterion("Ugrade <>", value, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUgradeGreaterThan(Integer value) {
            addCriterion("Ugrade >", value, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUgradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("Ugrade >=", value, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUgradeLessThan(Integer value) {
            addCriterion("Ugrade <", value, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUgradeLessThanOrEqualTo(Integer value) {
            addCriterion("Ugrade <=", value, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUgradeIn(List<Integer> values) {
            addCriterion("Ugrade in", values, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUgradeNotIn(List<Integer> values) {
            addCriterion("Ugrade not in", values, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUgradeBetween(Integer value1, Integer value2) {
            addCriterion("Ugrade between", value1, value2, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUgradeNotBetween(Integer value1, Integer value2) {
            addCriterion("Ugrade not between", value1, value2, "ugrade");
            return (Criteria) this;
        }

        public Criteria andUnameIsNull() {
            addCriterion("Uname is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("Uname is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("Uname =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("Uname <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("Uname >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("Uname >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("Uname <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("Uname <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("Uname like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("Uname not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("Uname in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("Uname not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("Uname between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("Uname not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUemailIsNull() {
            addCriterion("Uemail is null");
            return (Criteria) this;
        }

        public Criteria andUemailIsNotNull() {
            addCriterion("Uemail is not null");
            return (Criteria) this;
        }

        public Criteria andUemailEqualTo(String value) {
            addCriterion("Uemail =", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotEqualTo(String value) {
            addCriterion("Uemail <>", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailGreaterThan(String value) {
            addCriterion("Uemail >", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailGreaterThanOrEqualTo(String value) {
            addCriterion("Uemail >=", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLessThan(String value) {
            addCriterion("Uemail <", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLessThanOrEqualTo(String value) {
            addCriterion("Uemail <=", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLike(String value) {
            addCriterion("Uemail like", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotLike(String value) {
            addCriterion("Uemail not like", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailIn(List<String> values) {
            addCriterion("Uemail in", values, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotIn(List<String> values) {
            addCriterion("Uemail not in", values, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailBetween(String value1, String value2) {
            addCriterion("Uemail between", value1, value2, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotBetween(String value1, String value2) {
            addCriterion("Uemail not between", value1, value2, "uemail");
            return (Criteria) this;
        }

        public Criteria andUtelIsNull() {
            addCriterion("Utel is null");
            return (Criteria) this;
        }

        public Criteria andUtelIsNotNull() {
            addCriterion("Utel is not null");
            return (Criteria) this;
        }

        public Criteria andUtelEqualTo(String value) {
            addCriterion("Utel =", value, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelNotEqualTo(String value) {
            addCriterion("Utel <>", value, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelGreaterThan(String value) {
            addCriterion("Utel >", value, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelGreaterThanOrEqualTo(String value) {
            addCriterion("Utel >=", value, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelLessThan(String value) {
            addCriterion("Utel <", value, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelLessThanOrEqualTo(String value) {
            addCriterion("Utel <=", value, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelLike(String value) {
            addCriterion("Utel like", value, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelNotLike(String value) {
            addCriterion("Utel not like", value, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelIn(List<String> values) {
            addCriterion("Utel in", values, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelNotIn(List<String> values) {
            addCriterion("Utel not in", values, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelBetween(String value1, String value2) {
            addCriterion("Utel between", value1, value2, "utel");
            return (Criteria) this;
        }

        public Criteria andUtelNotBetween(String value1, String value2) {
            addCriterion("Utel not between", value1, value2, "utel");
            return (Criteria) this;
        }

        public Criteria andUdeptIsNull() {
            addCriterion("Udept is null");
            return (Criteria) this;
        }

        public Criteria andUdeptIsNotNull() {
            addCriterion("Udept is not null");
            return (Criteria) this;
        }

        public Criteria andUdeptEqualTo(String value) {
            addCriterion("Udept =", value, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptNotEqualTo(String value) {
            addCriterion("Udept <>", value, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptGreaterThan(String value) {
            addCriterion("Udept >", value, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptGreaterThanOrEqualTo(String value) {
            addCriterion("Udept >=", value, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptLessThan(String value) {
            addCriterion("Udept <", value, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptLessThanOrEqualTo(String value) {
            addCriterion("Udept <=", value, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptLike(String value) {
            addCriterion("Udept like", value, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptNotLike(String value) {
            addCriterion("Udept not like", value, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptIn(List<String> values) {
            addCriterion("Udept in", values, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptNotIn(List<String> values) {
            addCriterion("Udept not in", values, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptBetween(String value1, String value2) {
            addCriterion("Udept between", value1, value2, "udept");
            return (Criteria) this;
        }

        public Criteria andUdeptNotBetween(String value1, String value2) {
            addCriterion("Udept not between", value1, value2, "udept");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 06 20:21:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}