package Demo.model;

import java.util.Objects;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Uid
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Upsd
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String upsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Ugrade
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private Integer ugrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Uname
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Uemail
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String uemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Utel
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String utel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Udept
     *
     * @mbggenerated Tue Aug 06 20:21:23 CST 2019
     */
    private String udept;

    private String taken;
    private String uimage;

    public String getUimage() {
        return uimage;
    }

    public void setUimage(String uimage) {
        this.uimage = uimage;
    }

    public String getTaken() {
        return taken;
    }

    public void setTaken(String taken) {
        this.taken = taken;
    }

    public User() {

    }

    public User(String uid, String upsd, Integer ugrade, String uname, String uemail, String utel, String udept, String taken, String uimage) {
        this.uid = uid;
        this.upsd = upsd;
        this.ugrade = ugrade;
        this.uname = uname;
        this.uemail = uemail;
        this.utel = utel;
        this.udept = udept;
        this.taken = taken;
        this.uimage = uimage;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUpsd() {
        return upsd;
    }

    public void setUpsd(String upsd) {
        this.upsd = upsd;
    }

    public Integer getUgrade() {
        return ugrade;
    }

    public void setUgrade(Integer ugrade) {
        this.ugrade = ugrade;
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getUemail() {
        return uemail;
    }

    public void setUemail(String uemail) {
        this.uemail = uemail;
    }

    public String getUtel() {
        return utel;
    }

    public void setUtel(String utel) {
        this.utel = utel;
    }

    public String getUdept() {
        return udept;
    }

    public void setUdept(String udept) {
        this.udept = udept;
    }

    @Override
    public String toString() {
        return "User{" +
                "uid='" + uid + '\'' +
                ", upsd='" + upsd + '\'' +
                ", ugrade=" + ugrade +
                ", uname='" + uname + '\'' +
                ", uemail='" + uemail + '\'' +
                ", utel='" + utel + '\'' +
                ", udept='" + udept + '\'' +
                ", taken='" + taken + '\'' +
                ", uimage='" + uimage + '\'' +
                '}';
    }
}